meta_product_name: "Fresh Pics"
meta_title: "Fresh Pics - Find Tonight's Perfect Movie in Two Minutes!"
meta_description: "Just tell Fresh Pics what streaming services you have and what you're in the mood for, and we'll give you three great suggestions - no more endless scrolling!"
meta_image: "felix-mooneeram-evlkOfkQ5rE-unsplash.jpg" # should exist in `app/assets/images/`
